replicaCount: 1

image:
  repository: fxinnovation/awr
  tag: 0.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

configuration:
  endpoint:
    scheme: 'https'
    host: 'rocketchat.example.com'
  credentials:
    name: 'example'
    email: 'example@example.com'
    password: 'changeme'
  severity_colors:
    warning: '#ffa500'
    critical: '#ff0000'
  channel:
    default_channel_name: 'example'
