apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "alertmanager-webhook-rocketchat.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alertmanager-webhook-rocketchat.name" . }}
    helm.sh/chart: {{ include "alertmanager-webhook-rocketchat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "alertmanager-webhook-rocketchat.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "alertmanager-webhook-rocketchat.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWR_ENDPOINT_SCHEME
              value: {{ .Values.configuration.endpoint.scheme }}
            - name: AWR_ENDPOINT_HOST
              value: {{ .Values.configuration.endpoint.host }}
            - name: AWR_CREDENTIALS_NAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.credential_password_secret }}"
                  key: name
            - name: AWR_CREDENTIALS_EMAIL
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.credential_password_secret }}"
                  key: email
            - name: AWR_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.credential_password_secret }}"
                  key: password
            - name: AWR_SEVERITY_COLORS_WARNING
              value: {{ .Values.configuration.severity_colors.warning }}
            - name: AWR_SEVERITY_COLORS_CRITICAL
              value: {{ .Values.configuration.severity_colors.critical }}
            - name: AWR_CHANNEL_DEFAULT_CHANNEL_NAME
              value: {{ .Values.configuration.channel.default_channel_name }}
          ports:
            - name: http
              containerPort: 9876
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
